# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3zSF_advg4LEMp5_EuezylVhuWXXnud
"""



# ==========================================
# MARKET BASKET ANALYSIS PROJECT
# ==========================================

# Step 1: Upload Dataset
from google.colab import files
uploaded = files.upload()

# Step 2: Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from itertools import combinations
from collections import Counter

# Step 3: Load Dataset
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print("=================================")
print("DATASET OVERVIEW")
print("=================================")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("\nFirst 5 Records:")
print(df.head())

# ==========================================
# PRODUCT POPULARITY ANALYSIS
# ==========================================

print("\n=================================")
print("PRODUCT POPULARITY")
print("=================================")

product_counts = df.sum()
product_counts = product_counts.sort_values(ascending=False)

print(product_counts)

plt.figure(figsize=(12,6))
product_counts.plot(kind='bar')
plt.title("Most Purchased Products")
plt.xlabel("Products")
plt.ylabel("Purchase Count")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ==========================================
# ITEMS PER BASKET
# ==========================================

df['Items_Per_Basket'] = df.sum(axis=1)

print("\n=================================")
print("BASKET ANALYSIS")
print("=================================")

print("Average Items Per Basket:",
      round(df['Items_Per_Basket'].mean(), 2))

plt.figure(figsize=(8,5))
plt.hist(df['Items_Per_Basket'], bins=10)
plt.title("Items Per Basket Distribution")
plt.xlabel("Number of Items")
plt.ylabel("Frequency")
plt.show()

# ==========================================
# TOP PRODUCT COMBINATIONS
# ==========================================

print("\n=================================")
print("TOP PRODUCT PAIRS")
print("=================================")

pair_counter = Counter()

for _, row in df.iterrows():

    items = []

    for col in df.columns[:-1]:
        if row[col] == True:
            items.append(col)

    for pair in combinations(items, 2):
        pair_counter[pair] += 1

top_pairs = pair_counter.most_common(10)

for pair, count in top_pairs:
    print(pair, ":", count)

# ==========================================
# PRODUCT CORRELATION HEATMAP
# ==========================================

print("\nGenerating Heatmap...")

corr_matrix = df.iloc[:, :-1].corr()

plt.figure(figsize=(12,10))
sns.heatmap(
    corr_matrix,
    annot=False,
    cmap='coolwarm'
)

plt.title("Product Correlation Heatmap")
plt.show()

# ==========================================
# TOP 10 PRODUCTS CHART
# ==========================================

top10 = product_counts.head(10)

plt.figure(figsize=(10,5))
top10.plot(kind='bar')
plt.title("Top 10 Purchased Products")
plt.xlabel("Products")
plt.ylabel("Purchase Count")
plt.tight_layout()
plt.show()

# ==========================================
# SAVE OUTPUT FILE
# ==========================================

output_file = "market_basket_analysis_output.csv"

df.to_csv(output_file, index=False)

print("\n=================================")
print("PROJECT COMPLETED SUCCESSFULLY")
print("Output File Saved:", output_file)
print("=================================")